# Generated by Django 4.2 on 2023-08-10 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Image",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="webApp/static/database/")),
            ],
        ),
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("project_id", models.PositiveIntegerField(unique=True)),
                ("name", models.CharField(max_length=100)),
                ("year", models.IntegerField()),
                ("duration", models.CharField(max_length=50)),
                ("sector", models.CharField(max_length=50)),
                ("location", models.CharField(max_length=50)),
                ("description", models.TextField()),
                ("client", models.CharField(max_length=50)),
                ("isHome", models.BooleanField(default=False)),
                (
                    "images",
                    models.ManyToManyField(related_name="projects", to="webApp.image"),
                ),
            ],
        ),
    ]
