# Generated by Django 4.2 on 2023-08-10 03:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("webApp", "0004_image_thumbnail"),
    ]

    operations = [
        migrations.RenameField(
            model_name="image",
            old_name="image",
            new_name="url",
        ),
    ]
