# Generated by Django 4.2 on 2023-08-10 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("webApp", "0005_rename_image_image_url"),
    ]

    operations = [
        migrations.CreateModel(
            name="Client",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("email", models.EmailField(max_length=50)),
                ("phone", models.CharField(max_length=15)),
                ("address", models.TextField()),
                ("primary_contact", models.CharField(max_length=50)),
                ("description", models.CharField(max_length=200)),
            ],
        ),
    ]
