# Generated by Django 4.2 on 2023-08-10 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("webApp", "0008_alter_project_sector"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="sector",
            field=models.CharField(default="", max_length=50),
        ),
    ]
