# Generated by Django 4.2 on 2023-08-10 15:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("webApp", "0009_alter_project_sector"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="client",
            field=models.ForeignKey(
                blank=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="webApp.client",
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="duration",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name="project",
            name="location",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name="project",
            name="sector",
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
