# Generated by Django 4.2 on 2023-08-10 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("webApp", "0010_alter_project_client_alter_project_duration_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="client",
            name="my_projects",
            field=models.ManyToManyField(related_name="projects", to="webApp.project"),
        ),
    ]
