# Generated by Django 4.2 on 2023-08-10 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("webApp", "0011_client_my_projects"),
    ]

    operations = [
        migrations.AlterField(
            model_name="client",
            name="description",
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
