# Generated by Django 4.2 on 2023-08-23 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("webApp", "0012_alter_client_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="client",
            name="my_projects",
            field=models.ManyToManyField(
                blank=True, related_name="projects", to="webApp.project"
            ),
        ),
    ]
