# Generated by Django 4.2 on 2023-08-23 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("webApp", "0014_alter_project_client"),
    ]

    operations = [
        migrations.AlterField(
            model_name="client",
            name="primary_contact",
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
