# Generated by Django 4.2 on 2023-08-23 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("webApp", "0015_alter_client_primary_contact"),
    ]

    operations = [
        migrations.AlterField(
            model_name="client",
            name="address",
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name="client",
            name="description",
            field=models.TextField(blank=True),
        ),
    ]
