# Generated by Django 4.2 on 2023-08-23 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("webApp", "0016_alter_client_address_alter_client_description"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="client",
            name="primary_contact",
        ),
        migrations.AddField(
            model_name="client",
            name="fax",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name="client",
            name="phone",
            field=models.CharField(max_length=20),
        ),
    ]
