# Generated by Django 4.2 on 2023-09-19 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("webApp", "0020_rename_customers_customer"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="project",
            options={"ordering": ["project_id"]},
        ),
        migrations.RenameField(
            model_name="project",
            old_name="description",
            new_name="short_desc",
        ),
    ]
