# Generated by Django 4.2 on 2023-09-19 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("webApp", "0022_project_description_alter_project_short_desc"),
    ]

    operations = [
        migrations.RenameField(
            model_name="project",
            old_name="short_desc",
            new_name="shortDesc",
        ),
    ]
