# Generated by Django 4.2 on 2023-09-20 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("webApp", "0024_alter_project_shortdesc"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="images",
            field=models.ManyToManyField(
                blank=True, related_name="projects", to="webApp.image"
            ),
        ),
    ]
