# Generated by Django 4.2 on 2023-09-20 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("webApp", "0025_alter_project_images"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="project_id",
            field=models.PositiveIntegerField(),
        ),
    ]
