# Generated by Django 4.2 on 2023-09-20 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("webApp", "0026_alter_project_project_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="project_id",
            field=models.PositiveIntegerField(unique=True),
        ),
    ]
