# Generated by Django 4.0.6 on 2023-10-06 19:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webApp', '0027_alter_project_project_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='my_projects',
        ),
    ]
