# Generated by Django 4.0.6 on 2023-10-06 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webApp', '0028_remove_client_my_projects'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='url',
            field=models.ImageField(upload_to='elnahass-sonsgroup/staticfiles/database/'),
        ),
    ]
