# Generated by Django 4.0.6 on 2024-08-11 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webApp', '0029_alter_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='shortDesc',
            field=models.TextField(blank=True, max_length=215),
        ),
    ]
